### ISSUE TITLE
Questions about pix2pix and CycleGan availability

### ISSUE THREAD

**Issue by UndecidedBoy** [zhanglichao/generatedTIR_tracking#1]
Hello,

This ins't an issue, I was more wondering if you plan on releasing a version of your trained _pix2pix_ or/and _CycleGAN_ from the paper: _Synthetic data generation for end-to-end thermal infrared tracking_ ? 
Did you use the original implementation of _pix2pix_ and _CycleGAN_ or a Tensorflow/Pytorch implementation?
And can we expect the TIR images made from _pix2pix_ to be available as a dataset?

In the meantime, thanks for your time and efforts.

**Comment by zhanglichao** [comment]
Hi,

Thanks for your attention.
Yes, we use the default implementation of pix2pix on Pytorch version:
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix

And the detained implementation description can be found on the paper.
We also release the training models by our side.

As the these videos are generated for training trackers, which are good for fine-tuning, but for the total images visualization maybe staggered. So maybe now we just release these models and not the real images.

best

**Comment by UndecidedBoy** [comment]
Thank you very much for the detailed answers and the models!

Best Regards

**Comment by UndecidedBoy** [comment]
Hello,

Since I'm not having a question about the code, I'm not sure If I'm supposed to ask this here, but I'm trying to look at the average activation ratio of a layer. 
I'm not sure if I've missed something while reading your paper or the one from Xinhang Song et al. but I didn't understand how to calculate it.
My understanding is: 
- An image A is passed through the CNN,
- afterward, you look at each of the 96 features spaces of the first layer from AlexNet,
- and compute 96 scalars, corresponding respectively to the averages of the 96 features spaces after the activation function.
- Finally, the 96 scalars are saved in a vector.
- Now, an image B is passed through the CNN, giving us 96 scalars for image B like previously, but this time you add them to the previous 96 scalars saved in a vector and so on until the CNN has seen the whole data set.
- The elements in the vector are then divided by the number of images the CNN has seen, giving you the average activation ratio?

Did I miss something? (Or everything?)

In the meantime, thank you for your time and consideration.
