### ISSUE TITLE
pix2pix reports an error

### ISSUE THREAD

**Issue by ghost** [zhanglichao/generatedTIR_tracking#6]
Hi, thank you for sharing. I downloaded your weight file. But I encountered a problem using https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix. CycleGAN can generate thermal infrared images, but pix2pix reports an error. I enter the command in the terminal as: python test.py --dataroot ./datasets/visible/ --direction AtoB --model test --name net_G_pix2pix. But the error message is AttributeError: 'Sequential' object has no attribute 'model'.

**Comment by zhanglichao** [comment]
Hi,

I have uploaded the GAN code for generating synthetic images, given some changes for loading the models, you could refer to the code or directly use this code.

/Lichao

**Comment by ghost** [comment]
> Hi,
> 
> I have uploaded the GAN code for generating synthetic images, given some changes for loading the models, you could refer to the code or directly use this code.
> 
> /Lichao

Hello, I really appreciate your reply and the code Shared.I wish you more success.
